//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optimisation_Windows_Capet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optimisation_Windows_Capet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a21f0c57d6c30_3471419315121737655137 {
            get {
                object obj = ResourceManager.GetObject("5a21f0c57d6c30.3471419315121737655137", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DDU {
            get {
                object obj = ResourceManager.GetObject("DDU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HtmlAgilityPack {
            get {
                object obj = ResourceManager.GetObject("HtmlAgilityPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NVIDIAINSPECTOR {
            get {
                object obj = ResourceManager.GetObject("NVIDIAINSPECTOR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OOSU10 {
            get {
                object obj = ResourceManager.GetObject("OOSU10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DisplayDriverUninstaller Version=&quot;17.0.9.1&quot;&gt;
        ///	&lt;Settings&gt;
        ///		&lt;SelectedLanguage&gt;fr-FR&lt;/SelectedLanguage&gt;
        ///		&lt;RemoveMonitors&gt;True&lt;/RemoveMonitors&gt;
        ///		&lt;RemoveCrimsonCache&gt;True&lt;/RemoveCrimsonCache&gt;
        ///		&lt;RemoveAMDDirs&gt;False&lt;/RemoveAMDDirs&gt;
        ///		&lt;RemoveAMDAudioBus&gt;True&lt;/RemoveAMDAudioBus&gt;
        ///		&lt;RemoveAMDKMPFD&gt;True&lt;/RemoveAMDKMPFD&gt;
        ///		&lt;RemoveNvidiaDirs&gt;False&lt;/RemoveNvidiaDirs&gt;
        ///		&lt;RemovePhysX&gt;True&lt;/RemovePhysX&gt;
        ///		&lt;Remove3DTVPlay&gt;True&lt;/Remove3DTVPlay&gt;
        ///		&lt;RemoveGFE&gt;True&lt;/RemoveG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsFR {
            get {
                return ResourceManager.GetString("SettingsFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TinyNvidiaUpdateChecker {
            get {
                object obj = ResourceManager.GetObject("TinyNvidiaUpdateChecker", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
